### ISSUE TITLE
Allow Clay to be Made in the Wooden Crucible

### ISSUE THREAD

**Issue by Darkosto** [NovaMachina/ExNihiloSequentia#128]
Hello again!

Would you be able to allow a block of Clay to be made in the Wooden Crucible when it has 1000mb of Water and right clicked with a block of Dust? Currently, the only method of obtaining clay to move to the Fired Crucible is by waiting for an Iron Bucket or waiting for rain (which is why the Wooden Crucible was initially created so you did not have to wait for those 2 things and speed up early game a bit). 

Thanks!

**Comment by NovaMachina** [comment]
Thank you for the suggestion. I don't plan on building this feature in the near future because of the relative ease of getting iron from sieving and an upcoming fix to the wooden crucible that will allow for creation of water without a heat source. If the current drop rate of items that help to progress game play are not to your liking you are more than welcome to adjust the rates through a datapack or a CraftTweaker script.

Again, thank you for the suggestion!

**Comment by Darkosto** [comment]
Would you be willing to extend out the datapack functionality to allow crucible recipes to made with an item output rather than only liquid outputs? For example:

```json
{
  "type": "exnihilosequentia:fluid_item",
  "fluid": {
    "fluid": "minecraft:water"
  },
  "input": {
    "item": "exnihilosequentia:dust"
  },
  "result": {
    "item": "minecraft:clay"
  }
}
```

But with a type as a crucible then setting the crucible to wooden or fired?

**Comment by NovaMachina** [comment]
The functionality that you are requesting already exists using the barrel. The crucible's primary purpose is to break down items into fluids. The barrel's primary purpose is to create items/entities/fluids. For this reason, I would like to keep the two ideas separate.
