### ISSUE TITLE
Barrels and Mekanisms Logistical Transporters combo produces stuff out of thin air.

### ISSUE THREAD

**Issue by WhitePhant0m** [NovaMachina/ExNihiloSequentia#164]
**Describe the bug**
Mekanisms Logistical Transporters don't use the stuff they send into barrels, creating stuff out of thin air.

**To Reproduce**
Check additional context.

**Expected behavior**
For barrels to not create stuff out of thin air.

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.0.46
Ex Nihilo: Sequentia Version: 2.0.2.3
Mekanism Version: 10.0.21.448

**Additional context**
https://github.com/AllTheMods/atm6-sky/issues/38
https://github.com/AllTheMods/atm6-sky/issues/74
https://github.com/AllTheMods/atm6-sky/issues/47

**Comment by remplerus** [comment]
we know this and try to find the issue on our side, but it might be a bug with any pipes except for the Pipez mod. Also, do an issue report on mekanism github so they can also investigate and try to fix the bug on their side, if possible.

**Comment by pupnewfster** [comment]
> we know this and try to find the issue on our side, but it might be a bug with any pipes except for the Pipez mod. Also, do an issue report on mekanism github so they can also investigate and try to fix the bug on their side, if possible.

It took me less time to find the bug in your code using github than it took me to finish brushing my teeth.... You guys entirely ignore the simulate flag for inserting items and insert them when mods simulate to see how much can actually be inserted... https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/1.16/src/main/java/novamachina/exnihilosequentia/common/tileentity/barrel/BarrelInventoryHandler.java#L17

Edit: you may also want to consider moving your [copy](https://github.com/NovaMachina-Mods/ExNihiloSequentia/blob/1.16/src/main/java/novamachina/exnihilosequentia/common/tileentity/barrel/mode/CompostBarrelMode.java#L116) call inside of the addSolid if statement so that you are only copying it if you are actually going to be modifying it as otherwise if someone sets something up to try and insert something that doesn't go in all you will be doing is generating a bunch of copy calls and ItemStack copying can get rather expensive depending on what mods are doing with capabilities.
