### ISSUE TITLE
Certain Rats blocks don't render textures when sieved

### ISSUE THREAD

**Issue by PatRat621** [NovaMachina/ExNihiloSequentia#226]
When adding certain blocks from the Rats mod to be sieved, the textures don't render

1. Through Craft Tweaker, add cheese/garbage piles from rats to be sievable 
2. Attempt to sieve said blocks

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24396786/121789885-b9c17980-cbd1-11eb-9fa7-f84c31c86b8f.png)

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.36
Ex Nihilo: Sequentia Version: 1.16-2.0.2.7
Rats: 7.2.0-1.16.5
Citadel: 1.7.1
CraftTweaker: 7.1.0.314

[AB#72](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/72)

**Comment by lazynessmind** [comment]
Hi. This happens when the block registry name isn't the same as the texture, and the sieve uses the registry name to get the texture from the texture atlas.

#### In this case:
| Registry Name | Texture Name |
| - | - |
| rats:block_of_cheese | rats:cheese |
| rats:garbage_pile | rats:garbage_0, rats:garbage_1, rats:garbage_2 ...  |

This is my understanding of the problem, but I'm will research more on this to check if Minecraft binds the texture to the registry name or not.

#### Edit:

On further investigation, I changed the dirt texture and used it on the sieve.

![2021-06-14_17 29 21](https://user-images.githubusercontent.com/52864251/121926793-3c634980-cd36-11eb-82c5-6e30f4db03a3.png)

Even though I changed the texture, the sieve uses the dirt texture because of the sieve lookup by the registry name instead of using the texture.

**Comment by remplerus** [comment]
made a PR for that sieve texture bug, might come before 1.17 version
