### ISSUE TITLE
bug by right click with mods bucket

### ISSUE THREAD

**Issue by GalaxyOfZero** [NovaMachina/ExNihiloSequentia#286]
**Describe the bug**
when right click with a bucket from the mods Forbidden & Arcanus and Wooden buckets on a wooden crucible, turn into an bucket from Minecraft

**To Reproduce**
1. Place block ' wooden crucible'
2. Right click on ' Bucket, see describe'
3. Do thing ' turn into Minecraft bucket'

**Expected behavior**
report from modpack 
https://github.com/GalaxyOfZero/Skyfriends/issues/1

**Screenshots**
https://youtu.be/c1Gv9egGDDI

**Version**
Minecraft Version: 1.16.5
Forge Version: 32.2.5
Ex Nihilo: Sequentia Version: 1.16-20211123-032540.

[AB#103](https://dev.azure.com/novamachina/9b4371f9-393b-4d7d-8cb9-1f6c864e3511/_workitems/edit/103)

**Comment by ghost** [comment]
The Crucible isn't from Ex Nihilo but from ex compressum, which isn't our mod, so please report it to Ex Compressum github

**Comment by GalaxyOfZero** [comment]
I have also tested it on Ex Nihilo and it is the same bug

**Comment by NovaMachina** [comment]
I do not believe that this is an issue with Ex Nihilo. The buckets from Frobidden & Arcanus use the default FluidBucketWrapper which uses the Minecraft Forge FluidUtils#getFilledBucket method to determine which bucket to return. Since the fluid being filled is water, the aforementioned method returns the vanilla water bucket. I suspect that the same issue occurs with Wooden Buckets. I believe this may be an issue with Minecraft Forge and will see what I can uncover.

**Comment by NovaMachina** [comment]
To echo what [Blay said](https://github.com/ModdingForBlockheads/ExCompressum/issues/339#issuecomment-982045835): Ex Nihilo "uses Forge's default fluid handler interaction, this is either an issue in Forbidden & Arcanus or Forge."
