### ISSUE TITLE
recipes not showing in jei

### ISSUE THREAD

**Issue by benbenlaw** [NovaMachina/ExNihiloSequentia#66]
**Describe the bug**
recipes not showing in jei on a server

**Expected behavior**
recipes shown

**Screenshots**
![image](https://user-images.githubusercontent.com/42780877/99804249-9d28fb80-2b32-11eb-8211-a6b2e73f0d67.png)

but drops other ores in when used in game
**Version**
Minecraft Version: 1.16.3
Forge Version: 31.1.61
Ex Nihilo: Sequentia Version: 2020-08-09-11-59-99

**Additional context**
Stack traces and log files are nice to have. Submit all files through [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) and place the links here.

**Comment by NovaMachina** [comment]
Which version of Ex Nihilo are you using?

**Comment by benbenlaw** [comment]
latest

**Comment by benbenlaw** [comment]
1.3.0.2

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/99820689-0582d780-2b49-11eb-977d-b3fd8249562f.png)
randomly now showing this somethimes it shows nothing sometimes it works fine super starange

**Comment by accessdenied0** [comment]
I have this issue, too.

I can also add, by the first time checking the recipes in JEI, the recipes doesn't show up again.

In general the recipes not only seem to be bugged in JEI but also in game. The resources I get from sieving is really not that what is to expect. For example gravel sieved with a Diamond mesh doesn't give any Diamonds, within 30 mins sieving (used Clicker Mod)

I can post logs if needed.

Edit I saw the issue was related here: [Issue 65](https://github.com/NovaMachina/ExNihiloSequentia/issues/65)
