### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by firemaster1294** [NovaMachina/ExNihiloSequentia#94]
Ex Nihilo Sequentia crashes on mod startup

**To Reproduce**
1. Install mekanism and Ex Nihilo Sequentia plus the mekanism add-on

**Expected behavior**
No crash

**Version**
Minecraft Version: 1.16.4
Forge Version: 35.1.37
Ex Nihilo: Sequentia Version: 2.0.1.0

**Additional context**
https://pastebin.com/XpxSxaAR

**Comment by NovaMachina** [comment]
Following these reported steps and using the same versions, I was not able to reproduce this. Is there another mod that when added to the above steps causes the crash?

**Comment by firemaster1294** [comment]
Definitely one of the mods I'm running then that's causing the crash. I think the paste bin should show the complete list of installed mods? I'll see if I can isolate the problem mod. So far I've been able to solve this by removing the mekanism add on

**Comment by remplerus** [comment]
well maybe the latest.log or debug.log should be posted too because with those crashlogs you cant see what happened before

**Comment by Demonpriest** [comment]
I am having the same issue, though it doesnt always crash, sometimes it boots fine, sometimes crashes multiple times in succesion.

Version
Minecraft Version: 1.16.4
Forge Version: 35.1.37
Ex Nihilo: Sequentia Version: 2.0.1.0

Additional context
latest.log
https://pastebin.com/EFP8NskS

**Comment by MegaHakkero** [comment]
Same issue here.

Minecraft 1.16.4
Forge 35.1.37
Ex Nihilo Sequentia 2.0.1.0

Crash log is nearly identical to previous commenter. Something is passing a null event to ClientSetup.onColorHandlerEvent, causing getItemColors() to be a null method.

**Comment by NovaMachina** [comment]
I've added some error checking for this issue. Since I was unable to replicate the problem, can someone report if this fixed the issue? You can find the jar here: [2.0.1.1-rc1](https://jenkins.jacob-williams.me/job/Ex%20Nihilo%20Sequentia/55/)

**Comment by Demonpriest** [comment]
It might just be coincidence, but when i encountered this issue i was using the curse launcher, and since switching to GD recently, i have yet to experience a single crash.

**Comment by Zickfor** [comment]
my friend has same issue

[debug.log](https://github.com/NovaMachina-Mods/ExNihiloSequentia/files/5934871/debug.log)

**Comment by SyedFaisalAli** [comment]
@NovaMachina I encountered the same issue using the MultiMC Launcher in attempt to try Sky Bees modpack (https://www.curseforge.com/minecraft/modpacks/sky-bees)

Updating mod with your attached jar seems to have fixed the issue as I'm now able to get past the startup.

**Comment by Lazyshot** [comment]
I've updated the attached jar and still am having this issue both with Curse launcher and with MultiMC:

The big tell to me is the
```
[21:41:18] [Render thread/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: null
```

Note: This is Sky Bees modpack

Logs:
https://pastebin.com/kJYB0uCr

**Comment by Lazyshot** [comment]
Rolled Forge back to 35.1.36 and it is working now. May just be a bug in the latest build of Forge.

**Comment by NovaMachina** [comment]
Interesting....There are some logging statements that are created when `enableDebugLogging` is enabled in the config file. Someone who is having this issue, can you enable it and submit the log? Unfortunately I'm having to rely on y'all since I can't replicate the issue.

**Comment by cjo9900** [comment]
I had some time, cloned ExNihiloSequentia and ExNihiloSequentia-Mekanism and added some trace and managed to reproduce the issue seen.
My logging showed that NullPointer Exception in onColorHandlerEvent() is caused by ore.getChunkItem() returning a NULL for osmium.

Extra tracing showed the chunk and piece items were not being created for the ore.
As I noted that the chunk and pieces are created in ExNihiloItems.java#113 I added some trace there to see what was created at that point.
In the failure cases osmium was not in the EnumOre, in success cases osmium was present.

Adding trace to ExNihiloSequentia-Mekanism where createOres() is called ExNihiloMekanism.java#23, it was seen that this called after ExNihiloItems in the failure cases. So it looks to be a timing/ordering issue in when these are called. Adding other mods seems to alter the timing/ordering as a simple test with just the minimal mods required for the error do not seem to trigger. (I tried about 10 times and did not see the issue).

Minimal test case setup

mcVersion, 1.16.4
forgeVersion, 35.1.37
mcpVersion, 20201102.104115

Mekanism-1.16.4-10.0.19.446.jar
MekanismGenerators-1.16.4-10.0.19.446.jar
MekanismTools-1.16.4-10.0.19.446.jar
exnihilomekanism-1.16-1.0.0.0.jar
exnihilosequentia-1.16-2.0.1.0.jar or exnihilosequentia-1.16-2.0.1.1-rc1.jar


I haven't progressed any further as I don't understand the interaction and ordering of how these different parts are called.
But Hope this helps you track down a solution.

Example logs from my testing
The failure one came from Sky_Bees-3.0.2 modpack just replacing the two affected mods with my debug versions

Success case
https://gist.github.com/cjo9900/d921b4be94af737f83f998c08dddd196

Failure case
https://gist.github.com/cjo9900/78666ce3426bb8b749a9f5b1794cf2ba


Chris

**Comment by NovaMachina** [comment]
@cjo9900 Perfect, this helps a lot actually. I just haven't really had the time to sit down and do full out debugging since this was reported. Thanks for your help. Probably means that I need to go and rethink how I load in ores.

**Comment by NovaMachina** [comment]
Here is an RC for the [Mekanism Addon](https://jenkins.jacob-williams.me/job/Ex%20Nihilo%20Sequentia%20-%20Mekanism%20Addon/5/). I'm going to do some testing now and see what I come up with.

**Comment by sz55net** [comment]
Thanks @NovaMachina, that fixed it. I've had no issues so far. I'm going to message the Sky Bees owner, so they can do something.

**Comment by NovaMachina** [comment]
@homelyseven250 Which thing fixed it exactly?

**Comment by kylertlove** [comment]
I have not been able to replicate the issue after pulling down exnihilomekanism-1.16-1.0.0.1-rc1.  It seems that the ordering of addons before ExSeq fixes it.  

Tested with both forge 35.1.36 and 37
Ex Nihilo: Sequentia Version: 2.0.1.0
plus a dozen other random mods including Mekanism

**Comment by NovaMachina** [comment]
Ok perfect. I'll release this then.
